//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesignUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Good
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Good()
        {
            this.InvoiceDetails = new HashSet<InvoiceDetail>();
            this.GoodsReceiveds = new HashSet<GoodsReceived>();
        }
    
        public string ID { get; set; }
        public string Name { get; set; }
        public Nullable<double> Price { get; set; }
        public string Brand { get; set; }
        public Nullable<bool> Hide { get; set; }
        public string Catagory { get; set; }
        public Nullable<System.DateTime> MFG { get; set; }
        public Nullable<System.DateTime> EXP { get; set; }
        public string Unit { get; set; }
        public Nullable<int> InventoryNumber { get; set; }
        public Nullable<int> ShipmentNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceDetail> InvoiceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodsReceived> GoodsReceiveds { get; set; }
    }
}
