//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesignUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceDetail
    {
        public string ID_Goods { get; set; }
        public string ID_Invoice { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> Total { get; set; }
    
        public virtual Good Good { get; set; }
        public virtual Invoice Invoice { get; set; }
    }
}
