//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesignUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shift
    {
        public string Shift1 { get; set; }
        public string Counter { get; set; }
        public System.DateTime Date { get; set; }
        public string ID_Cashier { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
